[project]
name = "chunking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "attr>=0.3.2",
    "pandas>=2.2.3",
    "tiktoken>=0.9.0",
]
