database:
  path: data/db

corpus:
  path: data/corpora/wikitexts.md

queries:
  path: data/queries.csv

results:
  data_path: reports/results/data

experiments:
  embedding_function: all-MiniLM-L6-v2
  chunk_sizes:
    - 200
    - 400
    - 600
    - 800
    - 1000
  halfway_overlap:
    - True
    - False
  retrieve_count:
    - 3
    - 5
    - 7
    - 9
